name: blockscout-blocks-are-changing

on:
  # Triggered daily or manually in https://github.com/oasisprotocol/explorer/actions/workflows/blockscout-blocks-are-changing.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        api: [old-explorer.emerald.oasis.io, testnet.old-explorer.emerald.oasis.io/, old-explorer.sapphire.oasis.io, testnet.old-explorer.sapphire.oasis.io]

    name: '${{ matrix.api }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl "https://${{ matrix.api }}/blocks?type=JSON" --fail -o blocks
      - run: git add .
      - run: sleep 30s
        shell: bash
      - run: curl "https://${{ matrix.api }}/blocks?type=JSON" --fail -o blocks
      - name: Fail if nothing changed
        run: "! git diff --exit-code"
