name: grpc-testnet-nodes-are-responding

on:
  # Triggered daily or manually in https://github.com/oasisprotocol/explorer/actions/workflows/grpc-testnet-nodes-are-responding.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  testnet-consensus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl 'https://testnet.grpc.oasis.dev/oasis-core.Staking/Account' --fail -o response \
            -H 'accept: application/grpc-web-text' \
            -H 'content-type: application/grpc-web-text' \
            --data-raw 'AAAAACWiZW93bmVyVQDI56n6hfwaDqF3oyGqwejdrOFUWmZoZWlnaHQA'
      - name: Fail if empty response
        run: "[ -s response ]"

  testnet-emerald:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl 'https://testnet.grpc.oasis.dev/oasis-core.RuntimeClient/Query' --fail -o response \
            -H 'accept: application/grpc-web-text' \
            -H 'content-type: application/grpc-web-text' \
            --data-raw 'AAAAAHykZGFyZ3NYH6FnYWRkcmVzc1UAyOep+oX8Gg6hd6MhqsHo3azhVFplcm91bmQb//////////9mbWV0aG9kcWFjY291bnRzLkJhbGFuY2VzanJ1bnRpbWVfaWRYIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHLIIV5g1byn'
      - name: Fail if empty response
        run: "[ -s response ]"

  testnet-sapphire:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl 'https://testnet.grpc.oasis.dev/oasis-core.RuntimeClient/Query' --fail -o response \
            -H 'accept: application/grpc-web-text' \
            -H 'content-type: application/grpc-web-text' \
            --data-raw 'AAAAAHykZGFyZ3NYH6FnYWRkcmVzc1UAyOep+oX8Gg6hd6MhqsHo3azhVFplcm91bmQb//////////9mbWV0aG9kcWFjY291bnRzLkJhbGFuY2VzanJ1bnRpbWVfaWRYIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKbR4+v2Df9s'
      - name: Fail if empty response
        run: "[ -s response ]"

  testnet-cipher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl 'https://testnet.grpc.oasis.dev/oasis-core.RuntimeClient/Query' --fail -o response \
            -H 'accept: application/grpc-web-text' \
            -H 'content-type: application/grpc-web-text' \
            --data-raw 'AAAAAHykZGFyZ3NYH6FnYWRkcmVzc1UAyOep+oX8Gg6hd6MhqsHo3azhVFplcm91bmQb//////////9mbWV0aG9kcWFjY291bnRzLkJhbGFuY2VzanJ1bnRpbWVfaWRYIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
      - name: Fail if empty response
        run: "[ -s response ]"
