name: indexer-analyzers-are-running

on:
  # Triggered daily or manually in https://github.com/oasisprotocol/explorer/actions/workflows/oasisscan-blocks-are-changing.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tx_volume:
    strategy:
      fail-fast: false
      matrix:
        api: [nexus.prd.oasis.io, testnet.nexus.prd.oasis.io, nexus-blue-mainnet.prd0-gke.oasis.io, nexus-blue-testnet.prd0-gke.oasis.io, nexus.prg-gke1.oasis.io, nexus-testnet.prg-gke1.oasis.io]
        layer: [consensus, emerald, sapphire, pontusxtest, pontusxdev]
        exclude:
          - { api: nexus.prd.oasis.io, layer: pontusxtest }
          - { api: nexus.prd.oasis.io, layer: pontusxdev }
          - { api: nexus-blue-mainnet.prd0-gke.oasis.io, layer: pontusxtest }
          - { api: nexus-blue-mainnet.prd0-gke.oasis.io, layer: pontusxdev }
          - { api: nexus.prg-gke1.oasis.io, layer: pontusxtest }
          - { api: nexus.prg-gke1.oasis.io, layer: pontusxdev }

    name: 'tx_volume ${{ matrix.api }} ${{ matrix.layer }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./check_aggregate_not_far_behind.sh "${{ matrix.layer == 'consensus' && format('https://{0}/v1/', matrix.api) || format('https://{0}/v1/{1}/status', matrix.api, matrix.layer) }}" "https://${{ matrix.api }}/v1/${{ matrix.layer }}/stats/tx_volume?window_size_seconds=300&window_step_seconds=300&limit=1"

  active_accounts:
    strategy:
      fail-fast: false
      matrix:
        api: [nexus.prd.oasis.io, testnet.nexus.prd.oasis.io, nexus-blue-mainnet.prd0-gke.oasis.io, nexus-blue-testnet.prd0-gke.oasis.io]
        layer: [consensus, emerald, sapphire, pontusxtest, pontusxdev]
        exclude:
          - { api: nexus.prd.oasis.io, layer: pontusxtest }
          - { api: nexus.prd.oasis.io, layer: pontusxdev }
          - { api: nexus-blue-mainnet.prd0-gke.oasis.io, layer: pontusxtest }
          - { api: nexus-blue-mainnet.prd0-gke.oasis.io, layer: pontusxdev }

    name: 'active_accounts ${{ matrix.api }} ${{ matrix.layer }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./check_aggregate_not_far_behind.sh "${{ matrix.layer == 'consensus' && format('https://{0}/v1/', matrix.api) || format('https://{0}/v1/{1}/status', matrix.api, matrix.layer) }}" "https://${{ matrix.api }}/v1/${{ matrix.layer }}/stats/active_accounts?window_step_seconds=300&limit=1"

  epochs:
    strategy:
      fail-fast: false
      matrix:
        api: [nexus.prd.oasis.io, testnet.nexus.prd.oasis.io, nexus-blue-mainnet.prd0-gke.oasis.io, nexus-blue-testnet.prd0-gke.oasis.io]
    name: 'epoch ${{ matrix.api }} consensus'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./check_epoch_not_far_behind.sh "${{ format('https://{0}/v1/', matrix.api) }}" "https://${{ matrix.api }}/v1/consensus/epochs?limit=1"

  validator_history:
    strategy:
      fail-fast: false
      matrix:
        api: [nexus.prd.oasis.io, testnet.nexus.prd.oasis.io, nexus-blue-mainnet.prd0-gke.oasis.io, nexus-blue-testnet.prd0-gke.oasis.io]
    name: 'validator_history ${{ matrix.api }} consensus'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./check_validator_history_not_far_behind.sh "https://${{ matrix.api }}/v1/consensus/epochs?limit=1" "https://${{ matrix.api }}/v1/consensus/validators/${{ contains(matrix.api, 'testnet') && 'oasis1qqv25adrld8jjquzxzg769689lgf9jxvwgjs8tha' || 'oasis1qq3xrq0urs8qcffhvmhfhz4p0mu7ewc8rscnlwxe' }}/history?limit=1"
