name: indexer-blocks-are-changing

on:
  # Triggered daily or manually in https://github.com/oasisprotocol/explorer/actions/workflows/indexer-blocks-are-changing.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        api: [nexus.prd.oasis.io, testnet.nexus.prd.oasis.io, nexus.stg.oasis.io, testnet.nexus.stg.oasis.io]
        layer: [consensus, emerald, sapphire, pontusx]
        exclude:
          - { api: nexus.prd.oasis.io, layer: pontusx }
          - { api: nexus.stg.oasis.io, layer: pontusx }

    name: '${{ matrix.api }} ${{ matrix.layer }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://nexus.prd.oasis.io/v1/emerald/blocks
      # https://testnet.nexus.stg.oasis.io/v1/consensus/blocks
      - run: curl "https://${{ matrix.api }}/v1/${{ matrix.layer }}/blocks" --fail -o blocks
      - run: git add .
      - run: sleep 120s
        shell: bash
      - run: curl "https://${{ matrix.api }}/v1/${{ matrix.layer }}/blocks" --fail -o blocks
      - name: Fail if nothing changed
        run: "! git diff --exit-code"
